services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book_social_network'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    container_name: postgres-sql-bsn
    networks:
      - spring-demo
    restart: unless-stopped
    ports:
      - "5432:5432"

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local