services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book_social_network'
      - 'POSTGRES_PASSWORD=username'
      - 'POSTGRES_USER=password'
      - 'PGDATA: /var/lib/postresql/data'
    ports:
      - '5432:5432'
    container_name: postgres-sql-bsn
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local