/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookHistoryResponse {
  archived?: boolean;
  authorName?: string;
  cover?: Array<string>;
  id?: number;
  isbn?: string;
  owner?: string;
  rate?: number;
  returned?: boolean;
  returnedApproved?: boolean;
  sharable?: boolean;
  synopsis?: string;
  title?: string;
}
